<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\Models\ciudad;
class ciudades_seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [

            ['estado_id' => 1, 'ciudad' => 'Maroa'],
            ['estado_id' => 1, 'ciudad' => 'Puerto Ayacucho'],
            ['estado_id' => 1, 'ciudad' => 'San Fernando de Atabapo'],
            ['estado_id' => 2, 'ciudad' => 'Anaco'],
            ['estado_id' => 2, 'ciudad' => 'Aragua de Barcelona'],
            ['estado_id' => 2, 'ciudad' => 'Barcelona'],
            ['estado_id' => 2, 'ciudad' => 'Boca de Uchire'],
            ['estado_id' => 2, 'ciudad' => 'Cantaura'],
            ['estado_id' => 2, 'ciudad' => 'Clarines'],
            ['estado_id' => 2, 'ciudad' => 'El Chaparro'],
            ['estado_id' => 2, 'ciudad' => 'El Pao Anzoátegui'],
            ['estado_id' => 2, 'ciudad' => 'El Tigre'],
            ['estado_id' => 2, 'ciudad' => 'El Tigrito'],
            ['estado_id' => 2, 'ciudad' => 'Guanape'],
            ['estado_id' => 2, 'ciudad' => 'Guanta'],
            ['estado_id' => 2, 'ciudad' => 'Lechería'],
            ['estado_id' => 2, 'ciudad' => 'Onoto'],
            ['estado_id' => 2, 'ciudad' => 'Pariaguán'],
            ['estado_id' => 2, 'ciudad' => 'Píritu'],
            ['estado_id' => 2, 'ciudad' => 'Puerto La Cruz'],
            ['estado_id' => 2, 'ciudad' => 'Puerto Píritu'],
            ['estado_id' => 2, 'ciudad' => 'Sabana de Uchire'],
            ['estado_id' => 2, 'ciudad' => 'San Mateo Anzoátegui'],
            ['estado_id' => 2, 'ciudad' => 'San Pablo Anzoátegui'],
            ['estado_id' => 2, 'ciudad' => 'San Tomé'],
            ['estado_id' => 2, 'ciudad' => 'Santa Ana de Anzoátegui'],
            ['estado_id' => 2, 'ciudad' => 'Santa Fe Anzoátegui'],
            ['estado_id' => 2, 'ciudad' => 'Santa Rosa'],
            ['estado_id' => 2, 'ciudad' => 'Soledad'],
            ['estado_id' => 2, 'ciudad' => 'Urica'],
            ['estado_id' => 2, 'ciudad' => 'Valle de Guanape'],
            ['estado_id' => 3, 'ciudad' => 'Achaguas'],
            ['estado_id' => 3, 'ciudad' => 'Biruaca'],
            ['estado_id' => 3, 'ciudad' => 'Bruzual'],
            ['estado_id' => 3, 'ciudad' => 'El Amparo'],
            ['estado_id' => 3, 'ciudad' => 'El Nula'],
            ['estado_id' => 3, 'ciudad' => 'Elorza'],
            ['estado_id' => 3, 'ciudad' => 'Guasdualito'],
            ['estado_id' => 3, 'ciudad' => 'Mantecal'],
            ['estado_id' => 3, 'ciudad' => 'Puerto Páez'],
            ['estado_id' => 3, 'ciudad' => 'San Fernando de Apure'],
            ['estado_id' => 3, 'ciudad' => 'San Juan de Payara'],
            ['estado_id' => 4, 'ciudad' => 'Barbacoas'],
            ['estado_id' => 4, 'ciudad' => 'Cagua'],
            ['estado_id' => 4, 'ciudad' => 'Camatagua'],
            ['estado_id' => 4, 'ciudad' => 'Choroní'],
            ['estado_id' => 4, 'ciudad' => 'Colonia Tovar'],
            ['estado_id' => 4, 'ciudad' => 'El Consejo'],
            ['estado_id' => 4, 'ciudad' => 'La Victoria'],
            ['estado_id' => 4, 'ciudad' => 'Las Tejerías'],
            ['estado_id' => 4, 'ciudad' => 'Magdaleno'],
            ['estado_id' => 4, 'ciudad' => 'Maracay'],
            ['estado_id' => 4, 'ciudad' => 'Ocumare de La Costa'],
            ['estado_id' => 4, 'ciudad' => 'Palo Negro'],
            ['estado_id' => 4, 'ciudad' => 'San Casimiro'],
            ['estado_id' => 4, 'ciudad' => 'San Mateo'],
            ['estado_id' => 4, 'ciudad' => 'San Sebastián'],
            ['estado_id' => 4, 'ciudad' => 'Santa Cruz de Aragua'],
            ['estado_id' => 4, 'ciudad' => 'Tocorón'],
            ['estado_id' => 4, 'ciudad' => 'Turmero'],
            ['estado_id' => 4, 'ciudad' => 'Villa de Cura'],
            ['estado_id' => 4, 'ciudad' => 'Zuata'],
            ['estado_id' => 5, 'ciudad' => 'Barinas'],
            ['estado_id' => 5, 'ciudad' => 'Barinitas'],
            ['estado_id' => 5, 'ciudad' => 'Barrancas'],
            ['estado_id' => 5, 'ciudad' => 'Calderas'],
            ['estado_id' => 5, 'ciudad' => 'Capitanejo'],
            ['estado_id' => 5, 'ciudad' => 'Ciudad Bolivia'],
            ['estado_id' => 5, 'ciudad' => 'El Cantón'],
            ['estado_id' => 5, 'ciudad' => 'Las Veguitas'],
            ['estado_id' => 5, 'ciudad' => 'Libertad de Barinas'],
            ['estado_id' => 5, 'ciudad' => 'Sabaneta'],
            ['estado_id' => 5, 'ciudad' => 'Santa Bárbara de Barinas'],
            ['estado_id' => 5, 'ciudad' => 'Socopó'],
            ['estado_id' => 6, 'ciudad' => 'Caicara del Orinoco'],
            ['estado_id' => 6, 'ciudad' => 'Canaima'],
            ['estado_id' => 6, 'ciudad' => 'Ciudad Bolívar'],
            ['estado_id' => 6, 'ciudad' => 'Ciudad Piar'],
            ['estado_id' => 6, 'ciudad' => 'El Callao'],
            ['estado_id' => 6, 'ciudad' => 'El Dorado'],
            ['estado_id' => 6, 'ciudad' => 'El Manteco'],
            ['estado_id' => 6, 'ciudad' => 'El Palmar'],
            ['estado_id' => 6, 'ciudad' => 'El Pao'],
            ['estado_id' => 6, 'ciudad' => 'Guasipati'],
            ['estado_id' => 6, 'ciudad' => 'Guri'],
            ['estado_id' => 6, 'ciudad' => 'La Paragua'],
            ['estado_id' => 6, 'ciudad' => 'Matanzas'],
            ['estado_id' => 6, 'ciudad' => 'Puerto Ordaz'],
            ['estado_id' => 6, 'ciudad' => 'San Félix'],
            ['estado_id' => 6, 'ciudad' => 'Santa Elena de Uairén'],
            ['estado_id' => 6, 'ciudad' => 'Tumeremo'],
            ['estado_id' => 6, 'ciudad' => 'Unare'],
            ['estado_id' => 6, 'ciudad' => 'Upata'],
            ['estado_id' => 7, 'ciudad' => 'Bejuma'],
            ['estado_id' => 7, 'ciudad' => 'Belén'],
            ['estado_id' => 7, 'ciudad' => 'Campo de Carabobo'],
            ['estado_id' => 7, 'ciudad' => 'Canoabo'],
            ['estado_id' => 7, 'ciudad' => 'Central Tacarigua'],
            ['estado_id' => 7, 'ciudad' => 'Chirgua'],
            ['estado_id' => 7, 'ciudad' => 'Ciudad Alianza'],
            ['estado_id' => 7, 'ciudad' => 'El Palito'],
            ['estado_id' => 7, 'ciudad' => 'Guacara'],
            ['estado_id' => 7, 'ciudad' => 'Guigue'],
            ['estado_id' => 7, 'ciudad' => 'Las Trincheras'],
            ['estado_id' => 7, 'ciudad' => 'Los Guayos'],
            ['estado_id' => 7, 'ciudad' => 'Mariara'],
            ['estado_id' => 7, 'ciudad' => 'Miranda'],
            ['estado_id' => 7, 'ciudad' => 'Montalbán'],
            ['estado_id' => 7, 'ciudad' => 'Morón'],
            ['estado_id' => 7, 'ciudad' => 'Naguanagua'],
            ['estado_id' => 7, 'ciudad' => 'Puerto Cabello'],
            ['estado_id' => 7, 'ciudad' => 'San Joaquín'],
            ['estado_id' => 7, 'ciudad' => 'Tocuyito'],
            ['estado_id' => 7, 'ciudad' => 'Urama'],
            ['estado_id' => 7, 'ciudad' => 'Valencia'],
            ['estado_id' => 7, 'ciudad' => 'Vigirimita'],
            ['estado_id' => 8, 'ciudad' => 'Aguirre'],
            ['estado_id' => 8, 'ciudad' => 'Apartaderos Cojedes'],
            ['estado_id' => 8, 'ciudad' => 'Arismendi'],
            ['estado_id' => 8, 'ciudad' => 'Camuriquito'],
            ['estado_id' => 8, 'ciudad' => 'El Baúl'],
            ['estado_id' => 8, 'ciudad' => 'El Limón'],
            ['estado_id' => 8, 'ciudad' => 'El Pao Cojedes'],
            ['estado_id' => 8, 'ciudad' => 'El Socorro'],
            ['estado_id' => 8, 'ciudad' => 'La Aguadita'],
            ['estado_id' => 8, 'ciudad' => 'Las Vegas'],
            ['estado_id' => 8, 'ciudad' => 'Libertad de Cojedes'],
            ['estado_id' => 8, 'ciudad' => 'Mapuey'],
            ['estado_id' => 8, 'ciudad' => 'Piñedo'],
            ['estado_id' => 8, 'ciudad' => 'Samancito'],
            ['estado_id' => 8, 'ciudad' => 'San Carlos'],
            ['estado_id' => 8, 'ciudad' => 'Sucre'],
            ['estado_id' => 8, 'ciudad' => 'Tinaco'],
            ['estado_id' => 8, 'ciudad' => 'Tinaquillo'],
            ['estado_id' => 8, 'ciudad' => 'Vallecito'],
            ['estado_id' => 9, 'ciudad' => 'Tucupita'],
            ['estado_id' => 24, 'ciudad' => 'Caracas'],
            ['estado_id' => 24, 'ciudad' => 'El Junquito'],
            ['estado_id' => 10, 'ciudad' => 'Adícora'],
            ['estado_id' => 10, 'ciudad' => 'Boca de Aroa'],
            ['estado_id' => 10, 'ciudad' => 'Cabure'],
            ['estado_id' => 10, 'ciudad' => 'Capadare'],
            ['estado_id' => 10, 'ciudad' => 'Capatárida'],
            ['estado_id' => 10, 'ciudad' => 'Chichiriviche'],
            ['estado_id' => 10, 'ciudad' => 'Churuguara'],
            ['estado_id' => 10, 'ciudad' => 'Coro'],
            ['estado_id' => 10, 'ciudad' => 'Cumarebo'],
            ['estado_id' => 10, 'ciudad' => 'Dabajuro'],
            ['estado_id' => 10, 'ciudad' => 'Judibana'],
            ['estado_id' => 10, 'ciudad' => 'La Cruz de Taratara'],
            ['estado_id' => 10, 'ciudad' => 'La Vela de Coro'],
            ['estado_id' => 10, 'ciudad' => 'Los Taques'],
            ['estado_id' => 10, 'ciudad' => 'Maparari'],
            ['estado_id' => 10, 'ciudad' => 'Mene de Mauroa'],
            ['estado_id' => 10, 'ciudad' => 'Mirimire'],
            ['estado_id' => 10, 'ciudad' => 'Pedregal'],
            ['estado_id' => 10, 'ciudad' => 'Píritu Falcón'],
            ['estado_id' => 10, 'ciudad' => 'Pueblo Nuevo Falcón'],
            ['estado_id' => 10, 'ciudad' => 'Puerto Cumarebo'],
            ['estado_id' => 10, 'ciudad' => 'Punta Cardón'],
            ['estado_id' => 10, 'ciudad' => 'Punto Fijo'],
            ['estado_id' => 10, 'ciudad' => 'San Juan de Los Cayos'],
            ['estado_id' => 10, 'ciudad' => 'San Luis'],
            ['estado_id' => 10, 'ciudad' => 'Santa Ana Falcón'],
            ['estado_id' => 10, 'ciudad' => 'Santa Cruz De Bucaral'],
            ['estado_id' => 10, 'ciudad' => 'Tocopero'],
            ['estado_id' => 10, 'ciudad' => 'Tocuyo de La Costa'],
            ['estado_id' => 10, 'ciudad' => 'Tucacas'],
            ['estado_id' => 10, 'ciudad' => 'Yaracal'],
            ['estado_id' => 11, 'ciudad' => 'Altagracia de Orituco'],
            ['estado_id' => 11, 'ciudad' => 'Cabruta'],
            ['estado_id' => 11, 'ciudad' => 'Calabozo'],
            ['estado_id' => 11, 'ciudad' => 'Camaguán'],
            ['estado_id' => 11, 'ciudad' => 'Chaguaramas Guárico'],
            ['estado_id' => 11, 'ciudad' => 'El Socorro'],
            ['estado_id' => 11, 'ciudad' => 'El Sombrero'],
            ['estado_id' => 11, 'ciudad' => 'Las Mercedes de Los Llanos'],
            ['estado_id' => 11, 'ciudad' => 'Lezama'],
            ['estado_id' => 11, 'ciudad' => 'Onoto'],
            ['estado_id' => 11, 'ciudad' => 'Ortíz'],
            ['estado_id' => 11, 'ciudad' => 'San José de Guaribe'],
            ['estado_id' => 11, 'ciudad' => 'San Juan de Los Morros'],
            ['estado_id' => 11, 'ciudad' => 'San Rafael de Laya'],
            ['estado_id' => 11, 'ciudad' => 'Santa María de Ipire'],
            ['estado_id' => 11, 'ciudad' => 'Tucupido'],
            ['estado_id' => 11, 'ciudad' => 'Valle de La Pascua'],
            ['estado_id' => 11, 'ciudad' => 'Zaraza'],
            ['estado_id' => 12, 'ciudad' => 'Aguada Grande'],
            ['estado_id' => 12, 'ciudad' => 'Atarigua'],
            ['estado_id' => 12, 'ciudad' => 'Barquisimeto'],
            ['estado_id' => 12, 'ciudad' => 'Bobare'],
            ['estado_id' => 12, 'ciudad' => 'Cabudare'],
            ['estado_id' => 12, 'ciudad' => 'Carora'],
            ['estado_id' => 12, 'ciudad' => 'Cubiro'],
            ['estado_id' => 12, 'ciudad' => 'Cují'],
            ['estado_id' => 12, 'ciudad' => 'Duaca'],
            ['estado_id' => 12, 'ciudad' => 'El Manzano'],
            ['estado_id' => 12, 'ciudad' => 'El Tocuyo'],
            ['estado_id' => 12, 'ciudad' => 'Guaríco'],
            ['estado_id' => 12, 'ciudad' => 'Humocaro Alto'],
            ['estado_id' => 12, 'ciudad' => 'Humocaro Bajo'],
            ['estado_id' => 12, 'ciudad' => 'La Miel'],
            ['estado_id' => 12, 'ciudad' => 'Moroturo'],
            ['estado_id' => 12, 'ciudad' => 'Quíbor'],
            ['estado_id' => 12, 'ciudad' => 'Río Claro'],
            ['estado_id' => 12, 'ciudad' => 'Sanare'],
            ['estado_id' => 12, 'ciudad' => 'Santa Inés'],
            ['estado_id' => 12, 'ciudad' => 'Sarare'],
            ['estado_id' => 12, 'ciudad' => 'Siquisique'],
            ['estado_id' => 12, 'ciudad' => 'Tintorero'],
            ['estado_id' => 13, 'ciudad' => 'Apartaderos Mérida'],
            ['estado_id' => 13, 'ciudad' => 'Arapuey'],
            ['estado_id' => 13, 'ciudad' => 'Bailadores'],
            ['estado_id' => 13, 'ciudad' => 'Caja Seca'],
            ['estado_id' => 13, 'ciudad' => 'Canaguá'],
            ['estado_id' => 13, 'ciudad' => 'Chachopo'],
            ['estado_id' => 13, 'ciudad' => 'Chiguara'],
            ['estado_id' => 13, 'ciudad' => 'Ejido'],
            ['estado_id' => 13, 'ciudad' => 'El Vigía'],
            ['estado_id' => 13, 'ciudad' => 'La Azulita'],
            ['estado_id' => 13, 'ciudad' => 'La Playa'],
            ['estado_id' => 13, 'ciudad' => 'Lagunillas Mérida'],
            ['estado_id' => 13, 'ciudad' => 'Mérida'],
            ['estado_id' => 13, 'ciudad' => 'Mesa de Bolívar'],
            ['estado_id' => 13, 'ciudad' => 'Mucuchíes'],
            ['estado_id' => 13, 'ciudad' => 'Mucujepe'],
            ['estado_id' => 13, 'ciudad' => 'Mucuruba'],
            ['estado_id' => 13, 'ciudad' => 'Nueva Bolivia'],
            ['estado_id' => 13, 'ciudad' => 'Palmarito'],
            ['estado_id' => 13, 'ciudad' => 'Pueblo Llano'],
            ['estado_id' => 13, 'ciudad' => 'Santa Cruz de Mora'],
            ['estado_id' => 13, 'ciudad' => 'Santa Elena de Arenales'],
            ['estado_id' => 13, 'ciudad' => 'Santo Domingo'],
            ['estado_id' => 13, 'ciudad' => 'Tabáy'],
            ['estado_id' => 13, 'ciudad' => 'Timotes'],
            ['estado_id' => 13, 'ciudad' => 'Torondoy'],
            ['estado_id' => 13, 'ciudad' => 'Tovar'],
            ['estado_id' => 13, 'ciudad' => 'Tucani'],
            ['estado_id' => 13, 'ciudad' => 'Zea'],
            ['estado_id' => 14, 'ciudad' => 'Araguita'],
            ['estado_id' => 14, 'ciudad' => 'Carrizal'],
            ['estado_id' => 14, 'ciudad' => 'Caucagua'],
            ['estado_id' => 14, 'ciudad' => 'Chaguaramas Miranda'],
            ['estado_id' => 14, 'ciudad' => 'Charallave'],
            ['estado_id' => 14, 'ciudad' => 'Chirimena'],
            ['estado_id' => 14, 'ciudad' => 'Chuspa'],
            ['estado_id' => 14, 'ciudad' => 'Cúa'],
            ['estado_id' => 14, 'ciudad' => 'Cupira'],
            ['estado_id' => 14, 'ciudad' => 'Curiepe'],
            ['estado_id' => 14, 'ciudad' => 'El Guapo'],
            ['estado_id' => 14, 'ciudad' => 'El Jarillo'],
            ['estado_id' => 14, 'ciudad' => 'Filas de Mariche'],
            ['estado_id' => 14, 'ciudad' => 'Guarenas'],
            ['estado_id' => 14, 'ciudad' => 'Guatire'],
            ['estado_id' => 14, 'ciudad' => 'Higuerote'],
            ['estado_id' => 14, 'ciudad' => 'Los Anaucos'],
            ['estado_id' => 14, 'ciudad' => 'Los Teques'],
            ['estado_id' => 14, 'ciudad' => 'Ocumare del Tuy'],
            ['estado_id' => 14, 'ciudad' => 'Panaquire'],
            ['estado_id' => 14, 'ciudad' => 'Paracotos'],
            ['estado_id' => 14, 'ciudad' => 'Río Chico'],
            ['estado_id' => 14, 'ciudad' => 'San Antonio de Los Altos'],
            ['estado_id' => 14, 'ciudad' => 'San Diego de Los Altos'],
            ['estado_id' => 14, 'ciudad' => 'San Fernando del Guapo'],
            ['estado_id' => 14, 'ciudad' => 'San Francisco de Yare'],
            ['estado_id' => 14, 'ciudad' => 'San José de Los Altos'],
            ['estado_id' => 14, 'ciudad' => 'San José de Río Chico'],
            ['estado_id' => 14, 'ciudad' => 'San Pedro de Los Altos'],
            ['estado_id' => 14, 'ciudad' => 'Santa Lucía'],
            ['estado_id' => 14, 'ciudad' => 'Santa Teresa'],
            ['estado_id' => 14, 'ciudad' => 'Tacarigua de La Laguna'],
            ['estado_id' => 14, 'ciudad' => 'Tacarigua de Mamporal'],
            ['estado_id' => 14, 'ciudad' => 'Tácata'],
            ['estado_id' => 14, 'ciudad' => 'Turumo'],
            ['estado_id' => 15, 'ciudad' => 'Aguasay'],
            ['estado_id' => 15, 'ciudad' => 'Aragua de Maturín'],
            ['estado_id' => 15, 'ciudad' => 'Barrancas del Orinoco'],
            ['estado_id' => 15, 'ciudad' => 'Caicara de Maturín'],
            ['estado_id' => 15, 'ciudad' => 'Caripe'],
            ['estado_id' => 15, 'ciudad' => 'Caripito'],
            ['estado_id' => 15, 'ciudad' => 'Chaguaramal'],
            ['estado_id' => 15, 'ciudad' => 'Chaguaramas Monagas'],
            ['estado_id' => 15, 'ciudad' => 'El Furrial'],
            ['estado_id' => 15, 'ciudad' => 'El Tejero'],
            ['estado_id' => 15, 'ciudad' => 'Jusepín'],
            ['estado_id' => 15, 'ciudad' => 'La Toscana'],
            ['estado_id' => 15, 'ciudad' => 'Maturín'],
            ['estado_id' => 15, 'ciudad' => 'Miraflores'],
            ['estado_id' => 15, 'ciudad' => 'Punta de Mata'],
            ['estado_id' => 15, 'ciudad' => 'Quiriquire'],
            ['estado_id' => 15, 'ciudad' => 'San Antonio de Maturín'],
            ['estado_id' => 15, 'ciudad' => 'San Vicente Monagas'],
            ['estado_id' => 15, 'ciudad' => 'Santa Bárbara'],
            ['estado_id' => 15, 'ciudad' => 'Temblador'],
            ['estado_id' => 15, 'ciudad' => 'Teresen'],
            ['estado_id' => 15, 'ciudad' => 'Uracoa'],
            ['estado_id' => 16, 'ciudad' => 'Altagracia'],
            ['estado_id' => 16, 'ciudad' => 'Boca de Pozo'],
            ['estado_id' => 16, 'ciudad' => 'Boca de Río'],
            ['estado_id' => 16, 'ciudad' => 'El Espinal'],
            ['estado_id' => 16, 'ciudad' => 'El Valle del Espíritu Santo'],
            ['estado_id' => 16, 'ciudad' => 'El Yaque'],
            ['estado_id' => 16, 'ciudad' => 'Juangriego'],
            ['estado_id' => 16, 'ciudad' => 'La Asunción'],
            ['estado_id' => 16, 'ciudad' => 'La Guardia'],
            ['estado_id' => 16, 'ciudad' => 'Pampatar'],
            ['estado_id' => 16, 'ciudad' => 'Porlamar'],
            ['estado_id' => 16, 'ciudad' => 'Puerto Fermín'],
            ['estado_id' => 16, 'ciudad' => 'Punta de Piedras'],
            ['estado_id' => 16, 'ciudad' => 'San Francisco de Macanao'],
            ['estado_id' => 16, 'ciudad' => 'San Juan Bautista'],
            ['estado_id' => 16, 'ciudad' => 'San Pedro de Coche'],
            ['estado_id' => 16, 'ciudad' => 'Santa Ana de Nueva Esparta'],
            ['estado_id' => 16, 'ciudad' => 'Villa Rosa'],
            ['estado_id' => 17, 'ciudad' => 'Acarigua'],
            ['estado_id' => 17, 'ciudad' => 'Agua Blanca'],
            ['estado_id' => 17, 'ciudad' => 'Araure'],
            ['estado_id' => 17, 'ciudad' => 'Biscucuy'],
            ['estado_id' => 17, 'ciudad' => 'Boconoito'],
            ['estado_id' => 17, 'ciudad' => 'Campo Elías'],
            ['estado_id' => 17, 'ciudad' => 'Chabasquén'],
            ['estado_id' => 17, 'ciudad' => 'Guanare'],
            ['estado_id' => 17, 'ciudad' => 'Guanarito'],
            ['estado_id' => 17, 'ciudad' => 'La Aparición'],
            ['estado_id' => 17, 'ciudad' => 'La Misión'],
            ['estado_id' => 17, 'ciudad' => 'Mesa de Cavacas'],
            ['estado_id' => 17, 'ciudad' => 'Ospino'],
            ['estado_id' => 17, 'ciudad' => 'Papelón'],
            ['estado_id' => 17, 'ciudad' => 'Payara'],
            ['estado_id' => 17, 'ciudad' => 'Pimpinela'],
            ['estado_id' => 17, 'ciudad' => 'Píritu de Portuguesa'],
            ['estado_id' => 17, 'ciudad' => 'San Rafael de Onoto'],
            ['estado_id' => 17, 'ciudad' => 'Santa Rosalía'],
            ['estado_id' => 17, 'ciudad' => 'Turén'],
            ['estado_id' => 18, 'ciudad' => 'Altos de Sucre'],
            ['estado_id' => 18, 'ciudad' => 'Araya'],
            ['estado_id' => 18, 'ciudad' => 'Cariaco'],
            ['estado_id' => 18, 'ciudad' => 'Carúpano'],
            ['estado_id' => 18, 'ciudad' => 'Casanay'],
            ['estado_id' => 18, 'ciudad' => 'Cumaná'],
            ['estado_id' => 18, 'ciudad' => 'Cumanacoa'],
            ['estado_id' => 18, 'ciudad' => 'El Morro Puerto Santo'],
            ['estado_id' => 18, 'ciudad' => 'El Pilar'],
            ['estado_id' => 18, 'ciudad' => 'El Poblado'],
            ['estado_id' => 18, 'ciudad' => 'Guaca'],
            ['estado_id' => 18, 'ciudad' => 'Guiria'],
            ['estado_id' => 18, 'ciudad' => 'Irapa'],
            ['estado_id' => 18, 'ciudad' => 'Manicuare'],
            ['estado_id' => 18, 'ciudad' => 'Mariguitar'],
            ['estado_id' => 18, 'ciudad' => 'Río Caribe'],
            ['estado_id' => 18, 'ciudad' => 'San Antonio del Golfo'],
            ['estado_id' => 18, 'ciudad' => 'San José de Aerocuar'],
            ['estado_id' => 18, 'ciudad' => 'San Vicente de Sucre'],
            ['estado_id' => 18, 'ciudad' => 'Santa Fe de Sucre'],
            ['estado_id' => 18, 'ciudad' => 'Tunapuy'],
            ['estado_id' => 18, 'ciudad' => 'Yaguaraparo'],
            ['estado_id' => 18, 'ciudad' => 'Yoco'],
            ['estado_id' => 19, 'ciudad' => 'Abejales'],
            ['estado_id' => 19, 'ciudad' => 'Borota'],
            ['estado_id' => 19, 'ciudad' => 'Bramon'],
            ['estado_id' => 19, 'ciudad' => 'Capacho'],
            ['estado_id' => 19, 'ciudad' => 'Colón'],
            ['estado_id' => 19, 'ciudad' => 'Coloncito'],
            ['estado_id' => 19, 'ciudad' => 'Cordero'],
            ['estado_id' => 19, 'ciudad' => 'El Cobre'],
            ['estado_id' => 19, 'ciudad' => 'El Pinal'],
            ['estado_id' => 19, 'ciudad' => 'Independencia'],
            ['estado_id' => 19, 'ciudad' => 'La Fría'],
            ['estado_id' => 19, 'ciudad' => 'La Grita'],
            ['estado_id' => 19, 'ciudad' => 'La Pedrera'],
            ['estado_id' => 19, 'ciudad' => 'La Tendida'],
            ['estado_id' => 19, 'ciudad' => 'Las Delicias'],
            ['estado_id' => 19, 'ciudad' => 'Las Hernández'],
            ['estado_id' => 19, 'ciudad' => 'Lobatera'],
            ['estado_id' => 19, 'ciudad' => 'Michelena'],
            ['estado_id' => 19, 'ciudad' => 'Palmira'],
            ['estado_id' => 19, 'ciudad' => 'Pregonero'],
            ['estado_id' => 19, 'ciudad' => 'Queniquea'],
            ['estado_id' => 19, 'ciudad' => 'Rubio'],
            ['estado_id' => 19, 'ciudad' => 'San Antonio del Tachira'],
            ['estado_id' => 19, 'ciudad' => 'San Cristobal'],
            ['estado_id' => 19, 'ciudad' => 'San José de Bolívar'],
            ['estado_id' => 19, 'ciudad' => 'San Josecito'],
            ['estado_id' => 19, 'ciudad' => 'San Pedro del Río'],
            ['estado_id' => 19, 'ciudad' => 'Santa Ana Táchira'],
            ['estado_id' => 19, 'ciudad' => 'Seboruco'],
            ['estado_id' => 19, 'ciudad' => 'Táriba'],
            ['estado_id' => 19, 'ciudad' => 'Umuquena'],
            ['estado_id' => 19, 'ciudad' => 'Ureña'],
            ['estado_id' => 20, 'ciudad' => 'Batatal'],
            ['estado_id' => 20, 'ciudad' => 'Betijoque'],
            ['estado_id' => 20, 'ciudad' => 'Boconó'],
            ['estado_id' => 20, 'ciudad' => 'Carache'],
            ['estado_id' => 20, 'ciudad' => 'Chejende'],
            ['estado_id' => 20, 'ciudad' => 'Cuicas'],
            ['estado_id' => 20, 'ciudad' => 'El Dividive'],
            ['estado_id' => 20, 'ciudad' => 'El Jaguito'],
            ['estado_id' => 20, 'ciudad' => 'Escuque'],
            ['estado_id' => 20, 'ciudad' => 'Isnotú'],
            ['estado_id' => 20, 'ciudad' => 'Jajó'],
            ['estado_id' => 20, 'ciudad' => 'La Ceiba'],
            ['estado_id' => 20, 'ciudad' => 'La Concepción de Trujllo'],
            ['estado_id' => 20, 'ciudad' => 'La Mesa de Esnujaque'],
            ['estado_id' => 20, 'ciudad' => 'La Puerta'],
            ['estado_id' => 20, 'ciudad' => 'La Quebrada'],
            ['estado_id' => 20, 'ciudad' => 'Mendoza Fría'],
            ['estado_id' => 20, 'ciudad' => 'Meseta de Chimpire'],
            ['estado_id' => 20, 'ciudad' => 'Monay'],
            ['estado_id' => 20, 'ciudad' => 'Motatán'],
            ['estado_id' => 20, 'ciudad' => 'Pampán'],
            ['estado_id' => 20, 'ciudad' => 'Pampanito'],
            ['estado_id' => 20, 'ciudad' => 'Sabana de Mendoza'],
            ['estado_id' => 20, 'ciudad' => 'San Lázaro'],
            ['estado_id' => 20, 'ciudad' => 'Santa Ana de Trujillo'],
            ['estado_id' => 20, 'ciudad' => 'Tostós'],
            ['estado_id' => 20, 'ciudad' => 'Trujillo'],
            ['estado_id' => 20, 'ciudad' => 'Valera'],
            ['estado_id' => 21, 'ciudad' => 'Carayaca'],
            ['estado_id' => 21, 'ciudad' => 'Litoral'],
            ['estado_id' => 25, 'ciudad' => 'Archipiélago Los Roques'],
            ['estado_id' => 22, 'ciudad' => 'Aroa'],
            ['estado_id' => 22, 'ciudad' => 'Boraure'],
            ['estado_id' => 22, 'ciudad' => 'Campo Elías de Yaracuy'],
            ['estado_id' => 22, 'ciudad' => 'Chivacoa'],
            ['estado_id' => 22, 'ciudad' => 'Cocorote'],
            ['estado_id' => 22, 'ciudad' => 'Farriar'],
            ['estado_id' => 22, 'ciudad' => 'Guama'],
            ['estado_id' => 22, 'ciudad' => 'Marín'],
            ['estado_id' => 22, 'ciudad' => 'Nirgua'],
            ['estado_id' => 22, 'ciudad' => 'Sabana de Parra'],
            ['estado_id' => 22, 'ciudad' => 'Salom'],
            ['estado_id' => 22, 'ciudad' => 'San Felipe'],
            ['estado_id' => 22, 'ciudad' => 'San Pablo de Yaracuy'],
            ['estado_id' => 22, 'ciudad' => 'Urachiche'],
            ['estado_id' => 22, 'ciudad' => 'Yaritagua'],
            ['estado_id' => 22, 'ciudad' => 'Yumare'],
            ['estado_id' => 23, 'ciudad' => 'Bachaquero'],
            ['estado_id' => 23, 'ciudad' => 'Bobures'],
            ['estado_id' => 23, 'ciudad' => 'Cabimas'],
            ['estado_id' => 23, 'ciudad' => 'Campo Concepción'],
            ['estado_id' => 23, 'ciudad' => 'Campo Mara'],
            ['estado_id' => 23, 'ciudad' => 'Campo Rojo'],
            ['estado_id' => 23, 'ciudad' => 'Carrasquero'],
            ['estado_id' => 23, 'ciudad' => 'Casigua'],
            ['estado_id' => 23, 'ciudad' => 'Chiquinquirá'],
            ['estado_id' => 23, 'ciudad' => 'Ciudad Ojeda'],
            ['estado_id' => 23, 'ciudad' => 'El Batey'],
            ['estado_id' => 23, 'ciudad' => 'El Carmelo'],
            ['estado_id' => 23, 'ciudad' => 'El Chivo'],
            ['estado_id' => 23, 'ciudad' => 'El Guayabo'],
            ['estado_id' => 23, 'ciudad' => 'El Mene'],
            ['estado_id' => 23, 'ciudad' => 'El Venado'],
            ['estado_id' => 23, 'ciudad' => 'Encontrados'],
            ['estado_id' => 23, 'ciudad' => 'Gibraltar'],
            ['estado_id' => 23, 'ciudad' => 'Isla de Toas'],
            ['estado_id' => 23, 'ciudad' => 'La Concepción del Zulia'],
            ['estado_id' => 23, 'ciudad' => 'La Paz'],
            ['estado_id' => 23, 'ciudad' => 'La Sierrita'],
            ['estado_id' => 23, 'ciudad' => 'Lagunillas del Zulia'],
            ['estado_id' => 23, 'ciudad' => 'Las Piedras de Perijá'],
            ['estado_id' => 23, 'ciudad' => 'Los Cortijos'],
            ['estado_id' => 23, 'ciudad' => 'Machiques'],
            ['estado_id' => 23, 'ciudad' => 'Maracaibo'],
            ['estado_id' => 23, 'ciudad' => 'Mene Grande'],
            ['estado_id' => 23, 'ciudad' => 'Palmarejo'],
            ['estado_id' => 23, 'ciudad' => 'Paraguaipoa'],
            ['estado_id' => 23, 'ciudad' => 'Potrerito'],
            ['estado_id' => 23, 'ciudad' => 'Pueblo Nuevo del Zulia'],
            ['estado_id' => 23, 'ciudad' => 'Puertos de Altagracia'],
            ['estado_id' => 23, 'ciudad' => 'Punta Gorda'],
            ['estado_id' => 23, 'ciudad' => 'Sabaneta de Palma'],
            ['estado_id' => 23, 'ciudad' => 'San Francisco'],
            ['estado_id' => 23, 'ciudad' => 'San José de Perijá'],
            ['estado_id' => 23, 'ciudad' => 'San Rafael del Moján'],
            ['estado_id' => 23, 'ciudad' => 'San Timoteo'],
            ['estado_id' => 23, 'ciudad' => 'Santa Bárbara Del Zulia'],
            ['estado_id' => 23, 'ciudad' => 'Santa Cruz de Mara'],
            ['estado_id' => 23, 'ciudad' => 'Santa Cruz del Zulia'],
            ['estado_id' => 23, 'ciudad' => 'Santa Rita'],
            ['estado_id' => 23, 'ciudad' => 'Sinamaica'],
            ['estado_id' => 23, 'ciudad' => 'Tamare'],
            ['estado_id' => 23, 'ciudad' => 'Tía Juana'],
            ['estado_id' => 23, 'ciudad' => 'Villa del Rosario'],
            ['estado_id' => 21, 'ciudad' => 'La Guaira'],
            ['estado_id' => 21, 'ciudad' => 'Catia La Mar'],
            ['estado_id' => 21, 'ciudad' => 'Macuto'],
            ['estado_id' => 21, 'ciudad' => 'Naiguatá'],
            ['estado_id' => 25, 'ciudad' => 'Archipiélago Los Monjes'],
            ['estado_id' => 25, 'ciudad' => 'Isla La Tortuga y Cayos adyacentes'],
            ['estado_id' => 25, 'ciudad' => 'Isla La Sola'],
            ['estado_id' => 25, 'ciudad' => 'Islas Los Testigos'],
            ['estado_id' => 25, 'ciudad' => 'Islas Los Frailes'],
            ['estado_id' => 25, 'ciudad' => 'Isla La Orchila'],
            ['estado_id' => 25, 'ciudad' => 'Archipiélago Las Aves'],
            ['estado_id' => 25, 'ciudad' => 'Isla de Aves'],
            ['estado_id' => 25, 'ciudad' => 'Isla La Blanquilla'],
            ['estado_id' => 25, 'ciudad' => 'Isla de Patos'],
            ['estado_id' => 25, 'ciudad' => 'Islas Los Hermanos']
        ];
        $now = Carbon::now();
        ciudad::insert($cities);
        ciudad::whereNotNull('ciudad')->update(['created_at' => $now, 'updated_at' => $now]);
    }
}
